/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { User, FinancialSummary } from "../types.js";

// Helper function to format currency for PDF (using ASCII "BDT" to prevent encoding errors)
const formatPDFCurrency = (val: number, fractionDigits = 0): string => {
  const parsed = Number(val);
  if (isNaN(parsed)) return "BDT 0";
  return "BDT " + parsed.toLocaleString("en-BD", {
    maximumFractionDigits: fractionDigits,
    minimumFractionDigits: fractionDigits,
  });
};

/**
 * Generates and downloads a structured, beautifully styled PDF summary of the project's financial status.
 * This includes the general financial KPIs, shareholder transactions ledger, and project expenses list.
 */
export function generateFinancialReportPDF(
  currentUser: User,
  summary: FinancialSummary,
  transactions: any[],
  expenses: any[]
): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Page dimensions: A4 is 210mm x 297mm
  const marginX = 14;
  let currentY = 15;

  // Function to draw professional dark header banner on the first page
  const drawHeaderBanner = () => {
    // Top Background Box (Dark Slate)
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 38, "F");

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("UN RIVER VIEW", marginX, 16);

    // Subtitle
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text("PROJECT FINANCIAL STATUS & AUDIT STATEMENT", marginX, 23);

    // Right-side meta details
    doc.setFontSize(8);
    doc.setTextColor(226, 232, 240); // slate-200
    const todayStr = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
    doc.text(`Generated On: ${todayStr}`, 210 - marginX - 65, 14);
    doc.text(`Generated By: ${currentUser.name} (${currentUser.role})`, 210 - marginX - 65, 20);
    doc.text("Security Class: Internal Shareholder Circ.", 210 - marginX - 65, 26);
  };

  // Draw header banner
  drawHeaderBanner();
  currentY = 48;

  // I. KEY FINANCIAL PORTFOLIO OVERVIEW
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("I. FINANCIAL PORTFOLIO OVERVIEW", marginX, currentY);

  // Accent horizontal line under section title
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.4);
  doc.line(marginX, currentY + 2, 210 - marginX, currentY + 2);

  currentY += 6;

  // Create KPI cards structure in table
  const overviewBody = [
    [
      "Total Share Value",
      formatPDFCurrency(summary.totalShareValue),
      "Current Balance",
      formatPDFCurrency(summary.currentBalance),
    ],
    [
      "Total Deposit",
      formatPDFCurrency(summary.totalDeposit),
      "Expense per Share",
      formatPDFCurrency(summary.expensePerShare, 2),
    ],
    [
      "Total Expense",
      formatPDFCurrency(summary.totalExpense),
      "Total Due Amount",
      formatPDFCurrency(summary.totalDue),
    ],
  ];

  autoTable(doc, {
    startY: currentY,
    body: overviewBody,
    theme: "grid",
    styles: {
      fontSize: 8.5,
      cellPadding: 4,
      font: "helvetica",
      lineColor: [226, 232, 240], // slate-200
      lineWidth: 0.3,
    },
    columnStyles: {
      0: { fontStyle: "bold", textColor: [71, 85, 105], fillColor: [248, 250, 252], cellWidth: 42 },
      1: { fontStyle: "bold", textColor: [15, 23, 42], halign: "right", cellWidth: 50 },
      2: { fontStyle: "bold", textColor: [71, 85, 105], fillColor: [248, 250, 252], cellWidth: 42 },
      3: { fontStyle: "bold", textColor: [15, 23, 42], halign: "right", cellWidth: 50 },
    },
    margin: { left: marginX, right: marginX },
  });

  currentY = (doc as any).lastAutoTable.finalY + 12;

  // II. RECENT SHAREHOLDER TRANSACTIONS LEDGER
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("II. RECENT SHAREHOLDER TRANSACTIONS", marginX, currentY);

  doc.setDrawColor(226, 232, 240);
  doc.line(marginX, currentY + 2, 210 - marginX, currentY + 2);

  currentY += 6;

  // Format transactions for the PDF table
  const txHeaders = [["Date", "TX ID", "Shareholder", "Type", "Amount", "Status", "Reference"]];
  const txRows = transactions.map((t) => [
    t.date,
    t.id,
    t.user,
    t.type,
    formatPDFCurrency(t.amount),
    t.status,
    t.reference || "-",
  ]);

  autoTable(doc, {
    startY: currentY,
    head: txHeaders,
    body: txRows,
    theme: "striped",
    styles: {
      fontSize: 8,
      cellPadding: 3.5,
      font: "helvetica",
    },
    headStyles: {
      fillColor: [30, 41, 59], // slate-800
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    columnStyles: {
      0: { fontStyle: "normal", textColor: [100, 116, 139] }, // date
      1: { fontStyle: "bold", textColor: [100, 116, 139] }, // id
      2: { fontStyle: "bold", textColor: [15, 23, 42] }, // user
      3: { fontStyle: "bold" }, // type
      4: { fontStyle: "bold", textColor: [15, 23, 42], halign: "right" }, // amount
      5: { fontStyle: "bold" }, // status
    },
    didDrawCell: (data) => {
      // Color-code the 'Type' and 'Status' text for high-end styling
      if (data.section === "body" && data.column.index === 3) {
        const typeStr = data.cell.raw as string;
        if (typeStr === "Deposit") {
          doc.setTextColor(16, 124, 65); // emerald-700
        } else {
          doc.setTextColor(225, 29, 72); // rose-600
        }
      }
      if (data.section === "body" && data.column.index === 5) {
        const statusStr = data.cell.raw as string;
        if (statusStr === "APPROVED") {
          doc.setTextColor(16, 124, 65); // green
        } else if (statusStr === "DECLINED") {
          doc.setTextColor(225, 29, 72); // red
        } else {
          doc.setTextColor(217, 119, 6); // amber-600 (Pending)
        }
      }
    },
    margin: { left: marginX, right: marginX },
  });

  currentY = (doc as any).lastAutoTable.finalY + 12;

  // Check if we need to insert a page break for the expenses section to keep spacing flawless
  if (currentY > 230) {
    doc.addPage();
    currentY = 20;
  }

  // III. RECENT PROJECT EXPENSES (OUTFLOWS)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("III. DETAILED PROJECT EXPENSES", marginX, currentY);

  doc.setDrawColor(226, 232, 240);
  doc.line(marginX, currentY + 2, 210 - marginX, currentY + 2);

  currentY += 6;

  // Format expenses for the PDF table
  const expenseHeaders = [["Date", "Expense Category", "Description", "Vendor", "Amount"]];
  const expenseRows = expenses.map((e) => [
    e.date,
    e.category,
    e.description || "-",
    e.vendor || "-",
    formatPDFCurrency(e.amount),
  ]);

  autoTable(doc, {
    startY: currentY,
    head: expenseHeaders,
    body: expenseRows,
    theme: "striped",
    styles: {
      fontSize: 8,
      cellPadding: 3.5,
      font: "helvetica",
    },
    headStyles: {
      fillColor: [30, 41, 59], // slate-800
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    columnStyles: {
      0: { fontStyle: "normal", textColor: [100, 116, 139] }, // date
      1: { fontStyle: "bold", textColor: [15, 23, 42] }, // category
      2: { fontStyle: "normal", textColor: [71, 85, 105] }, // description
      3: { fontStyle: "normal", textColor: [71, 85, 105] }, // vendor
      4: { fontStyle: "bold", textColor: [225, 29, 72], halign: "right" }, // amount is rose colored for outflows
    },
    margin: { left: marginX, right: marginX },
  });

  // Clean, professional footer with page numbering and security markings on every page
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184); // slate-400

    // Footer divider line
    doc.setDrawColor(241, 245, 249); // slate-100
    doc.setLineWidth(0.3);
    doc.line(marginX, 284, 210 - marginX, 284);

    // Footer Left text
    doc.text(
      `UN River View • Financial Status Report • Page ${i} of ${pageCount}`,
      marginX,
      289
    );

    // Footer Right text
    doc.text(
      "CONFIDENTIAL - FOR INTERNAL SHAREHOLDER DISTRIBUTION ONLY",
      210 - marginX,
      289,
      { align: "right" }
    );
  }

  // Trigger browser download
  const safeFilename = `un_river_view_financial_report_${new Date()
    .toISOString()
    .slice(0, 10)}.pdf`;
  doc.save(safeFilename);
}
